export const images = {
    slide1 : require("../assets/slide1.png"),
    bikeback:require("../assets/bikeback.png"),
    bikefront : require("../assets/bikefront.png"),
    bikef : require("../assets/bikef.png"),
    bikeb : require("../assets/bikeb.png"),
    user:require("../assets/user.png"),
    letsicon:require("../assets/letsicon.png"),
    reseticon:require("../assets/reseticon.png"),
    opticon:require("../assets/otpicon.png"),
    flag:require("../assets/flag.png"),
    manualCard:require("../assets/manualCard.png"),
    identify:require("../assets/identify.png"),
    bell:require("../assets/bell.png"),
    warning:require("../assets/warning.png"),
    bike:require("../assets/bike.png"),
    bikeFront2:require("../assets/bikeFront2.png"),
    helmet:require("../assets/helmet.svg"),
    logout:require("../assets/logout.png"),
    address:require("../assets/address.png"),
    edit:require("../assets/edit.png"),
    card:require("../assets/card.png"),
    chat:require("../assets/chat.png"),
    wallet:require("../assets/wallet.png")

}